function [results, allNames] = HRB_runDataset(csvPath, pipeline, opts)
%HRB_runDataset  Run HRB_runPipeline over a dataset defined by a CSV map.
%
%  The CSV (generated by HRB_generateSubjectMap) is the single source of
%  truth: it defines which files to process, their subject IDs, and which
%  subjects to exclude. Files not listed in the CSV are never touched.
%
%  USAGE
%    results = HRB_runDataset('/path/to/subject_map.csv', 'pipeline_full.json')
%    results = HRB_runDataset(csvPath, pipeline, RunFolder='/path/to/output')
%
%  REQUIRED ARGUMENTS
%    csvPath    string   path to subject_map.csv (output of HRB_generateSubjectMap)
%    pipeline   string   path to pipeline JSON
%
%  OPTIONAL NAME-VALUE ARGUMENTS
%    DataPath   string   folder containing EEG files.
%                        Default: same folder as csvPath.
%                        Override when the CSV lives elsewhere (e.g. project root).
%    RunFolder  string   shared output root for all subjects.
%                        Default: auto-generated timestamp under pwd/output/.
%
%  CSV FORMAT  (columns: filename, subject_id, exclude)
%    filename    — EEG file to load; extension drives format auto-detection
%    subject_id  — identifier used in BST, SaveName, and output folders
%    exclude     — 1 = skip this subject; 0 = process
%
% Author: Ettore Napoli - University of Bologna, 2026

arguments
    csvPath    string
    pipeline   string
    opts.DataPath   string = ""
    opts.RunFolder  string = ""
end

% --- Read and validate the CSV ---
if ~isfile(csvPath)
    error("HRB:CSVNotFound", "subject_map.csv not found: %s", csvPath);
end

T = readtable(csvPath, TextType='string', VariableNamingRule='preserve', Delimiter=',');

required = ["filename", "subject_id", "exclude"];
missing  = required(~ismember(required, T.Properties.VariableNames));
if ~isempty(missing)
    error("HRB:InvalidCSV", "subject_map.csv is missing columns: %s", ...
        strjoin(missing, ', '));
end

% Check for empty subject IDs before starting
emptyId = T.subject_id == "" | ismissing(T.subject_id);
if any(emptyId)
    error("HRB:EmptySubjectId", ...
        "subject_id is empty for: %s\nFill in subject_map.csv before running.", ...
        strjoin(T.filename(emptyId), ', '));
end

% Check for duplicate subject IDs — would cause BST collisions
[~, ia] = unique(T.subject_id);
if length(ia) < height(T)
    dupes = T.subject_id(setdiff(1:height(T), ia));
    error("HRB:DuplicateSubjectId", ...
        "Duplicate subject_id in CSV: %s", strjoin(dupes, ', '));
end

% --- Resolve data folder ---
if strlength(opts.DataPath) == 0
    dataPath = fileparts(csvPath);  % default: same folder as CSV
else
    dataPath = char(opts.DataPath);
end

% --- Shared output folder for all subjects ---
if strlength(opts.RunFolder) == 0
    runFolder = fullfile(pwd, "output", datestr(now, 'yyyymmdd_HHMMSS'));
else
    runFolder = char(opts.RunFolder);
end
if ~isfolder(runFolder), mkdir(runFolder); end

% --- Summary ---
nTotal    = height(T);
nExcluded = sum(T.exclude == 1);
nActive   = nTotal - nExcluded;
fprintf('[HRB_runDataset] %d subject(s) in CSV — %d excluded — %d to process\n', ...
    nTotal, nExcluded, nActive);
fprintf('[HRB_runDataset] Output folder: %s\n', runFolder);

% --- Per-subject loop ---
results = cell(nTotal, 1);
allNames = cell(nTotal, 1);

for i = 1:nTotal
    fname  = char(T.filename(i));
    subjId = char(T.subject_id(i));

    if T.exclude(i) == 1
        fprintf('[HRB_runDataset] (%d/%d) SKIPPED (exclude=1): %s\n', ...
            i, nTotal, fname);
        results{i} = struct('HRB_skipped', true, 'subject', subjId);
        allNames{i} = {};
        continue
    end

    fprintf('[HRB_runDataset] (%d/%d) Subject: %s — loading %s\n', ...
        i, nTotal, subjId, fname);

    try
        EEG         = local_autoload(dataPath, fname);
        EEG.subject = subjId;  % CSV is authoritative — always overwrite

        fprintf('[HRB_runDataset] (%d/%d) Running pipeline\n', i, nTotal);
        [results{i}, allNames{i}] = HRB_runPipeline(EEG, pipeline, OutputFolder=runFolder);

    catch ME
        warning('[HRB_runDataset] FAILED %s: %s', fname, ME.message);
        results{i} = struct( ...
            'HRB_failed', true,       ...
            'subject',    subjId,     ...
            'error',      ME.message, ...
            'stack',      ME.stack);
        allNames{i} = {};
    end
end

fprintf('[HRB_runDataset] Done. Output: %s\n', runFolder);
end


% =========================================================================
function EEG = local_autoload(dataPath, fname)
%local_autoload  Load EEG file based on file extension.
%
%  Built-in format map:
%    .vhdr          BrainVision          pop_loadbv        (native EEGLAB)
%    .set           EEGLAB               pop_loadset       (native EEGLAB)
%    .cnt           Neuroscan cont.      pop_loadcnt       (native EEGLAB)
%    .eeg           Neuroscan epoched    pop_loadeeg       (native EEGLAB)
%    .bdf / .edf    BioSemi / EDF        pop_biosig        (requires BioSig plugin)
%    .mff           EGI / Philips        pop_mffimport     (requires MFF plugin)
%    other          fallback             pop_fileio        (requires FieldTrip plugin)
%
%  NOTE: .eeg is also the BrainVision binary data file, but BV data is
%  always loaded via .vhdr — never point FilePattern at .eeg for BV data.

[~, ~, ext] = fileparts(fname);

switch lower(ext)

    case '.vhdr'
        EEG = pop_loadbv(dataPath, fname);

    case '.set'
        try
            EEG = pop_loadset('filename', fname, 'filepath', dataPath);
        catch ME
            % pop_loadset sometimes fails in vararg2str (history recording).
            % The data is already loaded at that point — fall back to direct
            % .mat load to recover it.
            if strcmp(ME.stack(1).name, 'vararg2str')
                tmp = load('-mat', fullfile(dataPath, fname));
                % Handle both saving conventions:
                %   - fields nested inside tmp.EEG  (save(f, 'EEG'))
                %   - fields at top level            (save(f, '-struct', 'EEG'))
                if isfield(tmp, 'EEG')
                    EEG = tmp.EEG;
                else
                    EEG = tmp;
                end
                % Load float data from external .fdt file if present
                if ~isnumeric(EEG.data) || isempty(EEG.data)
                    fid      = fopen(fullfile(dataPath, EEG.datfile), 'rb', 'ieee-le');
                    EEG.data = fread(fid, [EEG.nbchan Inf], 'float32');
                    fclose(fid);
                    if EEG.trials > 1
                        EEG.data = reshape(EEG.data, EEG.nbchan, EEG.pnts, EEG.trials);
                    end
                end
            else
                rethrow(ME);
            end
        end

    case '.cnt'
        % Neuroscan continuous — native EEGLAB loader, no plugin required.
        EEG = pop_loadcnt(fullfile(dataPath, fname));

    case '.eeg'
        % Neuroscan epoched — native EEGLAB loader, no plugin required.
        EEG = pop_loadeeg(fullfile(dataPath, fname));

    case {'.bdf', '.edf'}
        % BioSemi / EDF — requires BioSig plugin in EEGLAB.
        EEG = pop_biosig(fullfile(dataPath, fname));

    case '.mff'
        % EGI / Philips MFF — requires MFF plugin in EEGLAB.
        % Second argument: 'code' = import event codes only.
        EEG = pop_mffimport({fullfile(dataPath, fname)}, {'code'});

    otherwise
        % Unknown format — attempt pop_fileio as last resort.
        % Requires FieldTrip plugin in EEGLAB.
        warning('HRB:UnknownFormat', ...
            'Extension "%s" not in built-in map — trying pop_fileio. ' ,...
            'If it fails, pass a custom LoadFcn.', ext);
        EEG = pop_fileio(fullfile(dataPath, fname));
end
end